services:
  valkey:
    image: valkey/valkey
    ports:
      - ${BULLMQ_PORT}:6379
    volumes:
      - valkey_data:/data
  
  qdrant:
    image: qdrant/qdrant
    ports:
      - ${QDRANT_PORT}:6333
    volumes:
      - qdrant_data:/qdrant/storage
  
  app:
    build: .
    ports:
      - ${PORT}:8000
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - LOG_LEVEL=${LOG_LEVEL}
      - BULLMQ_HOST=${BULLMQ_HOST}
      - BULLMQ_PORT=${BULLMQ_PORT}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_COLLECTION=${QDRANT_COLLECTION}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}
      - AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_EMBEDDINGS_API_KEY=${AZURE_OPENAI_EMBEDDINGS_API_KEY}
      - AZURE_OPENAI_EMBEDDINGS_INSTANCE_NAME=${AZURE_OPENAI_EMBEDDINGS_INSTANCE_NAME}
      - AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME=${AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT_NAME}
      - AZURE_OPENAI_EMBEDDINGS_API_VERSION=${AZURE_OPENAI_EMBEDDINGS_API_VERSION}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - valkey
      - qdrant

volumes:
  valkey_data:
  qdrant_data: